# Generated by Django 5.2.1 on 2025-05-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfood',
            name='calorie_amount',
            field=models.IntegerField(default=0),
        ),
    ]
